default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: 123456

development:
  <<: *default
  database: message_development

test:
  <<: *default
  database: message_test

staging:
  <<: *default
  database: message_staging
  username: root
  password:

production:
  <<: *default
  database: message
  username: root
  password:
  server: localhost